nextcloud_version: 20.0.1
nextcloud_archive_hash: "96c6b50e1e676e46cec82d8f8ff1abd5eef9dfa00580081b6c640612c3ff2efc"
nextcloud_command:
  - php
  - /var/www/nextcloud/occ
  - --verbose
  - --no-interaction
