nextcloud_version: 20.0.13
nextcloud_archive_hash: "e9bd524c072309c84ead253f12b6840392db570d8503d6f3427544af5428b196"
nextcloud_command:
  - php
  - /var/www/nextcloud/occ
  - --verbose
  - --no-interaction
