---
- name: install php packages
  apt:
    pkg:
      - php{{ php_version }}-cli
      - php{{ php_version }}-imagick
      - php{{ php_version }}-fpm
      - php{{ php_version }}-bz2
      - php{{ php_version }}-curl
      - php{{ php_version }}-intl
      - php{{ php_version }}-gd
      - php{{ php_version }}-json
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-opcache
      - php{{ php_version }}-pgsql
      - php{{ php_version }}-xml
      - php{{ php_version }}-zip
      - libmagickcore-6.q16-6-extra
    state: present
  notify: "restart php"
