---
- name: download caddy
  get_url:
    # https://caddyserver.com/api/download?os=linux&arch=arm64&p=github.com%2Fcaddy-dns%2Fcloudflare&idempotency=7099745858578
    url: "{{ caddy_download_url }}\
    ?os=linux\
    &arch={{ caddy_arch }}\
    &telemetry=off\
    &p={{ caddy_plugins | join('&p=') }}"
    dest: /opt/caddy.tar.gz
    owner: root
    group: root
    mode: 0640
    timeout: 120

- name: create installation directory
  file:
    path: /opt/caddy
    state: directory
    owner: root
    group: root
    mode: 0755

- name: extract caddy archive
  unarchive:
    src: /opt/caddy.tar.gz
    dest: /opt/caddy
    remote_src: true
    creates: /opt/caddy/caddy
  notify: "restart caddy"

- name: link caddy
  file:
    src: /opt/caddy/caddy
    dest: /usr/local/bin/caddy
    state: link
    owner: root
    group: root
    mode: 0755
  notify: "restart caddy"

- name: create configuration home
  file:
    path: /etc/caddy
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create vhosts configuration home
  file:
    path: /etc/caddy/vhosts
    state: directory
    owner: root
    group: www-data
    mode: 0750

- name: create main configuration
  copy:
    src: etc/caddy/Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: root
    group: www-data
    mode: 0640
  notify: "restart caddy"

- name: check caddy env
  stat:
    path: /etc/default/caddy
  register: caddy_stat

- pause:
    prompt: "insert cloudflare dns api token"
  register: api_token
  when: not caddy_stat.stat.exists

- name: create caddy env
  template:
    src: etc/default/caddy.j2
    dest: /etc/default/caddy
    owner: root
    group: www-data
    mode: 0650
  when: not caddy_stat.stat.exists
  notify: "restart caddy"

- name: create caddypath
  file:
    path: /etc/ssl/caddy
    state: directory
    owner: root
    group: www-data
    mode: 0770

- name: create caddy log home
  file:
    path: /var/log/caddy
    state: directory
    owner: root
    group: www-data
    mode: 0770

- name: create dummy vhost home
  file:
    path: /var/www/dummy
    state: directory
    owner: root
    group: www-data
    mode: 0755

- name: create dummy vhost
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: www-data
    mode: 0644
  with_items:
    - etc/caddy/vhosts/dummy.conf
    - etc/caddy/content-encoding.conf
    - etc/caddy/realip-cloudflare.conf
    - etc/caddy/tls-cloudflare.conf
    - etc/caddy/strict-headers.conf
    - var/www/dummy/index.txt
  notify: "restart caddy"

- name: create systemd service
  template:
    src: etc/systemd/system/caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: 0644
  register: caddy_create_service

- debug:
    var: caddy_create_service.changed

- name: enable caddy
  systemd:
    name: caddy
    daemon_reload: "{{ caddy_create_service.changed }}"
    enabled: true
