---
- assert:
    that:
      - nextcloud_vhost | length > 0
      - nextcloud_admin_username | length > 0
      - nextcloud_admin_email | length > 0
      - nextcloud_admin_password | length > 0
  delegate_to: local

- name: download nextcloud
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.tar.bz2"
    dest: /opt/nextcloud.tar.bz2
    sha256sum: "{{ nextcloud_archive_hash }}"
    owner: root
    group: root

- file:
    path: /var/www/nextcloud
    state: directory

- name: extract nextcloud
  unarchive:
    src: /opt/nextcloud.tar.bz2
    dest: /var/www/nextcloud
    remote_src: true
    extra_opts:
      - --strip-components=1
    owner: root
    group: www-data
    creates: /var/www/nextcloud/occ

- name: nextcloud has a place to store data
  file:
    path: /var/www/nextcloud/data
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: nextcloud has write access where needed
  file:
    path: "/var/www/nextcloud/{{ item }}"
    owner: www-data
  with_items:
    - config
    - apps

- name: "create nextcloud database user"
  postgresql_user:
    name: "www-data"
    password: "1234"
    role_attr_flags: "LOGIN"
  become_user: "postgres"

- name: "create nextcloud database"
  postgresql_db:
    name: "nextcloud"
    encoding: "UTF-8"
    owner: "www-data"
  become_user: "postgres"

- name: run occ install
  command:
    argv: "{{ nextcloud_command + [
      'maintenance:install',
      '--database=pgsql',
      '--database-name=nextcloud',
      '--database-pass=1234',
      '--database-user=www-data',
      '--admin-user=' + nextcloud_admin_username,
      '--admin-email=' + nextcloud_admin_email,
      '--admin-pass=' + nextcloud_admin_password,
    ] }}"
    creates: /var/www/nextcloud/data/index.html
  become_user: www-data

- name: install apps
  command:
    argv: "{{ nextcloud_command + [ 'app:install', item ] }}"
  become_user: www-data
  register: app_install
  changed_when: "'already installed' not in app_install.stdout"
  failed_when: "'Error' in app_install.stdout"
  with_items: "{{ nextcloud_apps }}"

- name: run maintenance commands after install apps
  command:
    argv: "{{ nextcloud_command + [ 'db:add-missing-indices' ] }}"
  become_user: www-data
  register: output
  changed_when: '"\nAdding " in output.stdout'

- name: run maintenance commands after install apps
  command:
    argv: "{{ nextcloud_command + [ 'db:convert-filecache-bigint' ] }}"
  become_user: www-data
  register: output
  changed_when: 'output.stdout != "All tables already up to date!"'

- name: nextcloud accepts {{ nextcloud_vhost }} domain
  command: php /var/www/nextcloud/occ config:system:set trusted_domains 1 --value="{{ nextcloud_vhost }}"
  become_user: www-data

- name: nextcloud systemd cron exists
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - etc/systemd/system/nextcloud-cron.service
    - etc/systemd/system/nextcloud-cron.timer

- name: nextcloud systemd cron is enabled
  systemd:
    name: nextcloud-cron.timer
    state: started
    enabled: true
    daemon_reload: true

- name: nextcloud cron is setup
  command: php /var/www/nextcloud/occ config:app:set core backgroundjobs_mode --value=cron
  become_user: www-data

- name: install nextcloud vhost
  template:
    src: etc/caddy/vhosts/nextcloud.conf.j2
    dest: /etc/caddy/vhosts/{{ nextcloud_vhost }}.conf
    owner: root
    group: root
    mode: 0644
  notify: "restart caddy"
