- locale_gen:
    name: "{{ item }}"
  with_items:
    - en_GB.UTF-8
    - en_US.UTF-8
    - fr_BE.UTF-8

- hostname:
    name: "{{ inventory_hostname }}"

- name: install default packages
  apt:
    name:
      - bash-completion
      - curl
      - git
      - gpg
      - htop
      - lvm2
      - man
      - tmux
