---
#
# Global stuff
#
- hosts: auyfan_buster
  become: yes
  roles:
    - auyfan-buster

- hosts: all
  become: yes
  roles:
    - common

#
# Specific applications
#
- hosts: arf.home.bendem.be
  become: yes
  roles:
    - database-server
    - php-fpm
    - web-server
    - nextcloud

  handlers:
    - name: restart caddy
      systemd:
        name: caddy
        state: restarted
