---
#
# Global stuff
#
- hosts: auyfan_buster
  become: true
  roles:
    - auyfan-buster

- hosts: all
  become: true
  roles:
    - common

#
# Specific applications
#
- hosts: nextcloud
  become: true
  roles:
    - database-server
    - php-fpm
    - web-server
    - nextcloud

  handlers:
    - name: restart postgresql@{{ postgresql_version }}-main
      systemd:
        name: postgresql@{{ postgresql_version }}-main
        state: restarted

    - name: restart php
      systemd:
        name: php{{ php_version }}-fpm
        state: restarted

    - name: restart caddy
      systemd:
        name: caddy
        state: restarted
