---
#
# Global stuff
#
- hosts: auyfan_buster
  become: yes
  roles:
    - auyfan-buster

- hosts: all
  become: yes
  roles:
    - common

#
# Specific applications
#
- hosts: arf.home.bendem.be
  become: yes
  roles:
    - database-server
    - php-fpm
    - web-server

    - role: nextcloud
      vars:
        nextcloud_vhost: "arf.home.bendem.be"
        nextcloud_admin_username: "bendem"
        nextcloud_admin_email: "online+nextcloud-arf@bendem.be"
        nextcloud_admin_password: "1234"

  handlers:
    - name: restart postgresql@11-main
      systemd:
        name: postgresql@11-main
        state: restarted

    - name: restart php
      systemd:
        name: php7.3-fpm
        state: restarted

    - name: restart caddy
      systemd:
        name: caddy
        state: restarted
